# Generated by Django 4.0.4 on 2022-05-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default='/media/profiles/avatarz.png', null=True, upload_to='profiles'),
        ),
    ]
