# Generated by Django 4.0.4 on 2022-05-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default='/profiles/avatars.png', null=True, upload_to='profiles'),
        ),
    ]
