# Generated by Django 4.0.4 on 2022-05-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_person_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='billreceipt',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
