# Generated by Django 4.0.4 on 2022-05-11 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_monthtimer_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthtimer',
            name='current',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 13, 17, 31, 683350), null=True),
        ),
    ]
